/********************************************************************
* DataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDataDict();
extern void G__cpp_setup_inheritanceDataDict();
extern void G__cpp_setup_typetableDataDict();
extern void G__cpp_setup_memvarDataDict();
extern void G__cpp_setup_globalDataDict();
extern void G__cpp_setup_memfuncDataDict();
extern void G__cpp_setup_funcDataDict();
extern void G__set_cpp_environmentDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Data.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DataDictLN_TClass;
extern G__linked_taginfo G__DataDictLN_TBuffer;
extern G__linked_taginfo G__DataDictLN_TMemberInspector;
extern G__linked_taginfo G__DataDictLN_TObject;
extern G__linked_taginfo G__DataDictLN_string;
extern G__linked_taginfo G__DataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataDictLN_TObjArray;
extern G__linked_taginfo G__DataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataDictLN_TArrayI;
extern G__linked_taginfo G__DataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DataDictLN_TTree;
extern G__linked_taginfo G__DataDictLN_TFile;
extern G__linked_taginfo G__DataDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__DataDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DataDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DataDictLN_TSQLServer;
extern G__linked_taginfo G__DataDictLN_Channel_t;
extern G__linked_taginfo G__DataDictLN_MidasHeader;
extern G__linked_taginfo G__DataDictLN_CaenHeader;
extern G__linked_taginfo G__DataDictLN_UserHeader;
extern G__linked_taginfo G__DataDictLN_OdbSettings;
extern G__linked_taginfo G__DataDictLN_Data_t;
extern G__linked_taginfo G__DataDictLN_Run_t;

/* STUB derived class for protected member access */
