/********************************************************************
* EventDisplayDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EventDisplayDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEventDisplayDict();
extern void G__cpp_setup_inheritanceEventDisplayDict();
extern void G__cpp_setup_typetableEventDisplayDict();
extern void G__cpp_setup_memvarEventDisplayDict();
extern void G__cpp_setup_globalEventDisplayDict();
extern void G__cpp_setup_memfuncEventDisplayDict();
extern void G__cpp_setup_funcEventDisplayDict();
extern void G__set_cpp_environmentEventDisplayDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EventDisplay.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EventDisplayDictLN_TClass;
extern G__linked_taginfo G__EventDisplayDictLN_TBuffer;
extern G__linked_taginfo G__EventDisplayDictLN_TMemberInspector;
extern G__linked_taginfo G__EventDisplayDictLN_TObject;
extern G__linked_taginfo G__EventDisplayDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__EventDisplayDictLN_string;
extern G__linked_taginfo G__EventDisplayDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EventDisplayDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDisplayDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EventDisplayDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDisplayDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EventDisplayDictLN_TQObject;
extern G__linked_taginfo G__EventDisplayDictLN_TGWindow;
extern G__linked_taginfo G__EventDisplayDictLN_TGObject;
extern G__linked_taginfo G__EventDisplayDictLN_TGFrame;
extern G__linked_taginfo G__EventDisplayDictLN_TGCompositeFrame;
extern G__linked_taginfo G__EventDisplayDictLN_TGTextButton;
extern G__linked_taginfo G__EventDisplayDictLN_TGMainFrame;
extern G__linked_taginfo G__EventDisplayDictLN_TGPopupMenu;
extern G__linked_taginfo G__EventDisplayDictLN_TGCheckButton;
extern G__linked_taginfo G__EventDisplayDictLN_TGComboBox;
extern G__linked_taginfo G__EventDisplayDictLN_listlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR;
extern G__linked_taginfo G__EventDisplayDictLN_TGTextEntry;
extern G__linked_taginfo G__EventDisplayDictLN_TGMenuBar;
extern G__linked_taginfo G__EventDisplayDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__EventDisplayDictLN_TGTab;
extern G__linked_taginfo G__EventDisplayDictLN_TGStatusBar;
extern G__linked_taginfo G__EventDisplayDictLN_TGNumberEntryField;
extern G__linked_taginfo G__EventDisplayDictLN_TGNumberEntry;
extern G__linked_taginfo G__EventDisplayDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__EventDisplayDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDisplayDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EventDisplayDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EventDisplayDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EventDisplayDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EventDisplayDictLN_TH2D;
extern G__linked_taginfo G__EventDisplayDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EventDisplayDictLN_Run_t;
extern G__linked_taginfo G__EventDisplayDictLN_display;

/* STUB derived class for protected member access */
