//
// File generated by rootcint at Tue Nov 13 16:30:05 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME EventDisplayDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "EventDisplayDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void display_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_display(void *p);
   static void deleteArray_display(void *p);
   static void destruct_display(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::display*)
   {
      ::display *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::display >(0);
      static ::ROOT::TGenericClassInfo 
         instance("display", ::display::Class_Version(), "./EventDisplay.h", 61,
                  typeid(::display), DefineBehavior(ptr, ptr),
                  &::display::Dictionary, isa_proxy, 4,
                  sizeof(::display) );
      instance.SetDelete(&delete_display);
      instance.SetDeleteArray(&deleteArray_display);
      instance.SetDestructor(&destruct_display);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::display*)
   {
      return GenerateInitInstanceLocal((::display*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::display*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *display::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *display::Class_Name()
{
   return "display";
}

//______________________________________________________________________________
const char *display::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::display*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int display::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::display*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void display::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::display*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *display::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::display*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void display::Streamer(TBuffer &R__b)
{
   // Stream an object of class display.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(display::Class(),this);
   } else {
      R__b.WriteClassBuffer(display::Class(),this);
   }
}

//______________________________________________________________________________
void display::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class display.
      TClass *R__cl = ::display::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*PrintDialog", &PrintDialog);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMenuFile", &fMenuFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMenuOptions", &fMenuOptions);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMenuTools", &fMenuTools);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMenuBar", &fMenuBar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTabMenu", &fTabMenu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTabPlots", &fTabPlots);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fEcanvasMulti[100]", &fEcanvasMulti);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheck[11]", &fCheck);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheckNewtab", &fCheckNewtab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheckSameRange", &fCheckSameRange);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheckIntegratedSignals", &fCheckIntegratedSignals);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheckSingleCH", &fCheckSingleCH);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheckConvert", &fCheckConvert);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheckXt", &fCheckXt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheckYt", &fCheckYt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheckGridt", &fCheckGridt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheckManColorScale", &fCheckManColorScale);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheckFiltering", &fCheckFiltering);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheckDispSpec", &fCheckDispSpec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheckShowFilter", &fCheckShowFilter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCheckDBValues", &fCheckDBValues);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fEventID", &fEventID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCBUnit", &fCBUnit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCBFilterType", &fCBFilterType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCBf1Unit", &fCBf1Unit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCBf2Unit", &fCBf2Unit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCBGas", &fCBGas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChMap", &fChMap);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fButtonDraw", &fButtonDraw);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fButtonClear", &fButtonClear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGdriftVelocity", &TGdriftVelocity);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGchannelmapping", &TGchannelmapping);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGstripDistance", &TGstripDistance);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGsignalThreshold", &TGsignalThreshold);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGbinScaling", &TGbinScaling);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGgridChannel", &TGgridChannel);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGMaxTab", &TGMaxTab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGSingleCH", &TGSingleCH);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGcutoff1", &TGcutoff1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGcutoff2", &TGcutoff2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGFilterOrder", &TGFilterOrder);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGmaxColorRange", &TGmaxColorRange);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGCommand", &TGCommand);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TGPrinter", &TGPrinter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*stat", &stat);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*stat2", &stat2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*run", &run);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*h21", &h21);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*h22", &h22);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "currentRunName", (void*)&currentRunName);
      R__insp.InspectMember("string", (void*)&currentRunName, "currentRunName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nevent", &nevent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nchannel", &nchannel);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nsamples", &nsamples);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ngroup", &ngroup);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "duration", &duration);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "date", &date);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "printfName[80]", printfName);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*chMapping", &chMapping);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "SQLchannelMapping", &SQLchannelMapping);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "SQLdriftVelocity", &SQLdriftVelocity);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_display(void *p) {
      delete ((::display*)p);
   }
   static void deleteArray_display(void *p) {
      delete [] ((::display*)p);
   }
   static void destruct_display(void *p) {
      typedef ::display current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::display

/********************************************************
* EventDisplayDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableEventDisplayDict();

extern "C" void G__set_cpp_environmentEventDisplayDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("EventDisplay.h");
  G__cpp_reset_tagtableEventDisplayDict();
}
#include <new>
extern "C" int G__cpp_dllrevEventDisplayDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* display */
static int G__EventDisplayDict_868_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   display* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new display(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) display(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EventDisplayDictLN_display));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->Init();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->CheckUpAll();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->DisableAll();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->OpenFile();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->ChangeSameRange();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->ChangeFiltering();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->ChangeUseDB();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->ChangeChMap();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->ChangeMaxColorRange();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->CloseTab();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->CloseAllTabs();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->Draw();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->GetPreviousEvent();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->GetNextEvent();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->CreateCanvas(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->SaveCanvas();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->PrintCanvas();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->ExecPrint();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->GetRunInfo();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((display*) G__getstructoffset())->GetFileExt(*((string*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->GetMinMaxData((double*) G__int(libp->para[0]), (double*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->ImportSettings();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->ExportSettings();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) display::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) display::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) display::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      display::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((display*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) display::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) display::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) display::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EventDisplayDict_868_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) display::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef display G__Tdisplay;
static int G__EventDisplayDict_868_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (display*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((display*) (soff+(sizeof(display)*i)))->~G__Tdisplay();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (display*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((display*) (soff))->~G__Tdisplay();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* display */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncEventDisplayDict {
 public:
  G__Sizep2memfuncEventDisplayDict(): p(&G__Sizep2memfuncEventDisplayDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncEventDisplayDict::*p)();
};

size_t G__get_sizep2memfuncEventDisplayDict()
{
  G__Sizep2memfuncEventDisplayDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceEventDisplayDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EventDisplayDictLN_display))) {
     display *G__Lderived;
     G__Lderived=(display*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EventDisplayDictLN_display),G__get_linked_tagnum(&G__EventDisplayDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EventDisplayDictLN_display),G__get_linked_tagnum(&G__EventDisplayDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EventDisplayDictLN_display),G__get_linked_tagnum(&G__EventDisplayDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EventDisplayDictLN_display),G__get_linked_tagnum(&G__EventDisplayDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EventDisplayDictLN_display),G__get_linked_tagnum(&G__EventDisplayDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EventDisplayDictLN_display),G__get_linked_tagnum(&G__EventDisplayDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EventDisplayDictLN_display),G__get_linked_tagnum(&G__EventDisplayDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableEventDisplayDict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EventDisplayDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EventDisplayDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EventDisplayDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EventDisplayDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<TGListTreeItem*>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_listlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EventDisplayDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EventDisplayDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__EventDisplayDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__EventDisplayDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* display */
static void G__setup_memvardisplay(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EventDisplayDictLN_display));
   { display *p; p=(display*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGMainFrame),-1,-1,4,"PrintDialog=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGPopupMenu),-1,-1,4,"fMenuFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGPopupMenu),-1,-1,4,"fMenuOptions=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGPopupMenu),-1,-1,4,"fMenuTools=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGMenuBar),-1,-1,4,"fMenuBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGTab),-1,-1,4,"fTabMenu=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGTab),-1,-1,4,"fTabPlots=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TRootEmbeddedCanvas),-1,-1,4,"fEcanvasMulti[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheck[11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheckNewtab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheckSameRange=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheckIntegratedSignals=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheckSingleCH=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheckConvert=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheckXt=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheckYt=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheckGridt=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheckManColorScale=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheckFiltering=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheckDispSpec=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheckShowFilter=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGCheckButton),-1,-1,4,"fCheckDBValues=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGNumberEntry),-1,-1,4,"fEventID=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGComboBox),-1,-1,4,"fCBUnit=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGComboBox),-1,-1,4,"fCBFilterType=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGComboBox),-1,-1,4,"fCBf1Unit=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGComboBox),-1,-1,4,"fCBf2Unit=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGComboBox),-1,-1,4,"fCBGas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGComboBox),-1,-1,4,"fChMap=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGTextButton),-1,-1,4,"fButtonDraw=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGTextButton),-1,-1,4,"fButtonClear=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGNumberEntry),-1,-1,4,"TGdriftVelocity=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGNumberEntry),-1,-1,4,"TGchannelmapping=",0,"tttt*/");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGNumberEntry),-1,-1,4,"TGstripDistance=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGNumberEntry),-1,-1,4,"TGsignalThreshold=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGNumberEntry),-1,-1,4,"TGbinScaling=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGNumberEntry),-1,-1,4,"TGgridChannel=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGNumberEntry),-1,-1,4,"TGMaxTab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGNumberEntry),-1,-1,4,"TGSingleCH=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGNumberEntry),-1,-1,4,"TGcutoff1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGNumberEntry),-1,-1,4,"TGcutoff2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGNumberEntry),-1,-1,4,"TGFilterOrder=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGNumberEntryField),-1,-1,4,"TGmaxColorRange=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGTextEntry),-1,-1,4,"TGCommand=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGTextEntry),-1,-1,4,"TGPrinter=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGStatusBar),-1,-1,4,"stat=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TGStatusBar),-1,-1,4,"stat2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_Run_t),-1,-1,4,"run=",0,"only object needed for data aceess");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TH2D),-1,-1,4,"h21=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TH2D),-1,-1,4,"h22=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_string),-1,-1,4,"currentRunName=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"nevent=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"nchannel=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"nsamples=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"ngroup=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"duration=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("time_t"),-1,4,"date=",0,(char*)NULL);
   G__memvar_setup((void*)0,99,0,0,-1,-1,-1,4,"printfName[80]=",0,(char*)NULL);
   G__memvar_setup((void*)0,73,0,0,-1,-1,-1,4,"chMapping=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"SQLchannelMapping=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"SQLdriftVelocity=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EventDisplayDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarEventDisplayDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncdisplay(void) {
   /* display */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EventDisplayDictLN_display));
   G__memfunc_setup("display",758,G__EventDisplayDict_868_0_1, 105, G__get_linked_tagnum(&G__EventDisplayDictLN_display), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,G__EventDisplayDict_868_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CheckUpAll",956,G__EventDisplayDict_868_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DisableAll",973,G__EventDisplayDict_868_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OpenFile",786,G__EventDisplayDict_868_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangeSameRange",1465,G__EventDisplayDict_868_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangeFiltering",1514,G__EventDisplayDict_868_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangeUseDB",1017,G__EventDisplayDict_868_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangeChMap",1039,G__EventDisplayDict_868_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangeMaxColorRange",1880,G__EventDisplayDict_868_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseTab",781,G__EventDisplayDict_868_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseAllTabs",1177,G__EventDisplayDict_868_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Draw",398,G__EventDisplayDict_868_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPreviousEvent",1663,G__EventDisplayDict_868_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNextEvent",1217,G__EventDisplayDict_868_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateCanvas",1200,G__EventDisplayDict_868_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - title", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SaveCanvas",1003,G__EventDisplayDict_868_0_17, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintCanvas",1129,G__EventDisplayDict_868_0_18, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ExecPrint",914,G__EventDisplayDict_868_0_19, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRunInfo",993,G__EventDisplayDict_868_0_20, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFileExt",977,G__EventDisplayDict_868_0_21, 105, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMinMaxData",1252,G__EventDisplayDict_868_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"D - - 0 - min D - - 0 - max", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ImportSettings",1484,G__EventDisplayDict_868_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ExportSettings",1491,G__EventDisplayDict_868_0_24, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ProcessMessage",1444,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"l - 'Long_t' 0 - msg l - 'Long_t' 0 - parm1 "
"l - 'Long_t' 0 - parm2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__EventDisplayDict_868_0_26, 85, G__get_linked_tagnum(&G__EventDisplayDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&display::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__EventDisplayDict_868_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&display::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__EventDisplayDict_868_0_28, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&display::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__EventDisplayDict_868_0_29, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&display::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__EventDisplayDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__EventDisplayDict_868_0_33, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__EventDisplayDict_868_0_34, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&display::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__EventDisplayDict_868_0_35, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&display::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__EventDisplayDict_868_0_36, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&display::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__EventDisplayDict_868_0_37, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&display::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~display", 884, G__EventDisplayDict_868_0_38, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncEventDisplayDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalEventDisplayDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcEventDisplayDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__EventDisplayDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGPopupMenu = { "TGPopupMenu" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGCheckButton = { "TGCheckButton" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGComboBox = { "TGComboBox" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_listlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR = { "list<TGListTreeItem*,allocator<TGListTreeItem*> >" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGTextEntry = { "TGTextEntry" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGMenuBar = { "TGMenuBar" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGTab = { "TGTab" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGStatusBar = { "TGStatusBar" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGNumberEntryField = { "TGNumberEntryField" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TGNumberEntry = { "TGNumberEntry" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_TH2D = { "TH2D" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_Run_t = { "Run_t" , 99 , -1 };
G__linked_taginfo G__EventDisplayDictLN_display = { "display" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableEventDisplayDict() {
  G__EventDisplayDictLN_TClass.tagnum = -1 ;
  G__EventDisplayDictLN_TBuffer.tagnum = -1 ;
  G__EventDisplayDictLN_TMemberInspector.tagnum = -1 ;
  G__EventDisplayDictLN_TObject.tagnum = -1 ;
  G__EventDisplayDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__EventDisplayDictLN_string.tagnum = -1 ;
  G__EventDisplayDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__EventDisplayDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EventDisplayDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__EventDisplayDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EventDisplayDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__EventDisplayDictLN_TQObject.tagnum = -1 ;
  G__EventDisplayDictLN_TGWindow.tagnum = -1 ;
  G__EventDisplayDictLN_TGObject.tagnum = -1 ;
  G__EventDisplayDictLN_TGFrame.tagnum = -1 ;
  G__EventDisplayDictLN_TGCompositeFrame.tagnum = -1 ;
  G__EventDisplayDictLN_TGTextButton.tagnum = -1 ;
  G__EventDisplayDictLN_TGMainFrame.tagnum = -1 ;
  G__EventDisplayDictLN_TGPopupMenu.tagnum = -1 ;
  G__EventDisplayDictLN_TGCheckButton.tagnum = -1 ;
  G__EventDisplayDictLN_TGComboBox.tagnum = -1 ;
  G__EventDisplayDictLN_listlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR.tagnum = -1 ;
  G__EventDisplayDictLN_TGTextEntry.tagnum = -1 ;
  G__EventDisplayDictLN_TGMenuBar.tagnum = -1 ;
  G__EventDisplayDictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__EventDisplayDictLN_TGTab.tagnum = -1 ;
  G__EventDisplayDictLN_TGStatusBar.tagnum = -1 ;
  G__EventDisplayDictLN_TGNumberEntryField.tagnum = -1 ;
  G__EventDisplayDictLN_TGNumberEntry.tagnum = -1 ;
  G__EventDisplayDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__EventDisplayDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EventDisplayDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__EventDisplayDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__EventDisplayDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__EventDisplayDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__EventDisplayDictLN_TH2D.tagnum = -1 ;
  G__EventDisplayDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__EventDisplayDictLN_Run_t.tagnum = -1 ;
  G__EventDisplayDictLN_display.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableEventDisplayDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_string);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGPopupMenu);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGCheckButton);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGComboBox);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_listlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGTextEntry);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGMenuBar);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGTab);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGStatusBar);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGNumberEntryField);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TGNumberEntry);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_TH2D);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_Run_t);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EventDisplayDictLN_display),sizeof(display),-1,324608,(char*)NULL,G__setup_memvardisplay,G__setup_memfuncdisplay);
}
extern "C" void G__cpp_setupEventDisplayDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupEventDisplayDict()");
  G__set_cpp_environmentEventDisplayDict();
  G__cpp_setup_tagtableEventDisplayDict();

  G__cpp_setup_inheritanceEventDisplayDict();

  G__cpp_setup_typetableEventDisplayDict();

  G__cpp_setup_memvarEventDisplayDict();

  G__cpp_setup_memfuncEventDisplayDict();
  G__cpp_setup_globalEventDisplayDict();
  G__cpp_setup_funcEventDisplayDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncEventDisplayDict();
  return;
}
class G__cpp_setup_initEventDisplayDict {
  public:
    G__cpp_setup_initEventDisplayDict() { G__add_setup_func("EventDisplayDict",(G__incsetup)(&G__cpp_setupEventDisplayDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initEventDisplayDict() { G__remove_setup_func("EventDisplayDict"); }
};
G__cpp_setup_initEventDisplayDict G__cpp_setup_initializerEventDisplayDict;

